name: the_motion_hub
description: "A new Flutter project to showcase a dance video app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter-specific dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  path_provider: ^2.0.15
  flutter_email_sender: ^5.0.2
  shared_preferences: ^2.1.1
  video_player: ^2.5.1
  image_picker: ^0.8.7+4
  video_trimmer: ^2.0.1
  path: ^1.8.0
  permission_handler: ^10.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Define the assets used in the app
  assets:
    - assets/images/default_profile.png
    - assets/videos/
    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
    - assets/videos/video4.mp4